{% set name = "pybmoore" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pybmoore-{{ version }}.tar.gz
  sha256: d95371311e60b2e59a8dab609838799ca22831fc6f9d14199a560f5d9b5e7d1d

build:
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - python
    - setuptools >=46.4.0
    - wheel
    - cython
    - pip
  run:
    - python

test:
  imports:
    - pybmoore
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/amenezes/pybmoore
  summary: Python/Cython Boyer-Moore string-search algorithm
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
